version: '3.5'

services:
    mariadb:
        container_name: mariadb
        networks:
        - inception
        build:
            context: requirements/mariadb
            dockerfile: Dockerfile
        env_file: .env
        volumes:
        - mariadb:/var/lib/mysql
        restart: unless-stopped
        ports:
        - "3306:3306"
    nginx:
        container_name: nginx
        volumes:
        - wordpress:/var/www/html
        networks:
        - inception
        depends_on:
        - wordpress
        build:
            context: requirements/nginx
            dockerfile: Dockerfile
        ports:
        - "443:443"
        restart: on-failure
    wordpress:
        container_name: wordpress
        env_file: .env
        volumes:
        - wordpress:/var/www/html
        networks:
        - inception
        build:
            context: requirements/wordpress
            dockerfile: Dockerfile
        depends_on:
        - mariadb
        restart: on-failure
        ports:
        - "9000:9000"
volumes:
    wordpress:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/pfrances/data/wordpress'
    mariadb:
        driver: local
        driver_opts:
            type: 'none'
            o: 'bind'
            device: '/home/pfrances/data/mariadb'
networks:
    inception:
        driver: bridge
